---
apiVersion: 1
# List of data sources to delete from the database.
deleteDatasources:
  - name: Graphite
    orgId: 1
datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    orgId: 1
    url: http://localhost:9090/
    uid: bd8271c8-8fcf-4b50-bc21-db42577faa1d
    isDefault: true
    editable: true
